### ISSUE TITLE
Looking for contributors?

### ISSUE THREAD

**Issue by easherma** [indivisible-org/indivisible-map#133]
Hey all!

I'm a developer based in Chicago and active in the civic tech scene, partially with Chi Hack Night. 

I also volunteer with a relatively new non-profit called State Matters ( https://www.statematters.org/ ), which is focused on informing people about legislation and other activity going on at the state level. 

One of our big pushes for this election is helping to support and enable Ballot Parties across the state ( https://ballotpartyil.ballotready.org/ ). 

To facilitate this, we'd like to build some functionality into our site to list available events and have users be able to search them. 

We all think this project is great example of what we'd like to do, and I was curious about:

* what the license is for this project

* ya'll would be interested in some outside contributions/collaborations to make this more easily forkable for a variety of similar functions? 

* if you consider the architecture of the project set up well for that potentiality

* if you'd like help with documentation and code contributions along the way with the goal of me being able to fork off a version of this to use in our site (https://github.com/state-matters/state-matters-website)

**Comment by meganrm** [comment]
Hey, sorry I took so long to respond to this. If you are still interested in working on a more generic event + map searching tool let me know. I've build 3 different versions of this same sort of thing : https://github.com/townhallproject/townHallProject, https://github.com/townhallproject/THP-Pledge and this one. Additionally, town hall project tracks some state legislator's town halls, and we're expanding, which may be potential collaboration with state matters. Lastly, if you have availability to volunteer still and are no longer working on state matters, we are always looking for more help.
