### ISSUE TITLE
Events leaving the map in local time

### ISSUE THREAD

**Issue by mayaryair** [indivisible-org/indivisible-map#141]
Hi team, I haven't been able to test this so I'm not 100% sure what's happening, but I've heard reports that events are leaving the map not based on the local time of the event. I'm not sure what timezone they think it's in, but I believe the events are leaving the map too early, so I assume ET. Could you check what the current procedure is? We want events to leave the map after the local start time. Thanks!

**Comment by meganrm** [comment]
The check to remove events is a whole day, ie, if it's Friday, an event will only get removed if it occurred on that Thursday or earlier. Even with time zones this should be enough of a buffer that it doesn't matter.
