### ISSUE TITLE
If no user_group_name, display action_group_name

### ISSUE THREAD

**Issue by mayaryair** [indivisible-org/indivisible-map#142]
We're going to start passing through some events that don't have user_group_name, but do have action_group_name (or it might be event_group_name). We'd like for the map to display that group name when there isn't a user_group_name. 

There's at least one event on the map like this now, ID = 137550, title = Environmental Voter Project: work to get inactive environmentalists to vote, date = Sunday, March 17, 4:00 PM.

**Comment by mayaryair** [comment]
Hi Megan, we've got a bunch of events on the map without user_group_name right now but with group_name and they're not being displayed. One of them for example ID = 138707

**Comment by meganrm** [comment]
Hey, So I looked at this and I think it was because originally I was only displaying these custom group name values for campaign=19. I am going to remove that filter.

**Comment by mayaryair** [comment]
Yeah that was the right move! This looks good now, thanks!
