### ISSUE TITLE
Croton-on-Hudson Indivisible's name isn't updating on the group map

### ISSUE THREAD

**Issue by mayaryair** [indivisible-org/indivisible-map#144]
Croton-on-Hudson Indivisible 's name was updated in our CRM to CCoHOPE Indivisible. The old name is still appearing on the group map though.

**Comment by meganrm** [comment]
@mayaryair I fixed this individual issue, but there is a larger problem that I am getting a permission denied error for the prosterworks api. I'm trying to rule out that they didn't just change some header setting but if you know the key you gave me has expired or anything let me know.
