### ISSUE TITLE
Handle empty results in zip code search

### ISSUE THREAD

**Issue by walterbm** [indivisible-org/indivisible-map#146]
# Bug

Searching for events near my zip code ([11249](https://www.google.com/maps/place/Brooklyn,+NY+11249/@40.7119072,-73.9748231,15z)) on the Indivisible site I noticed that the map seems to crash when the the zip code lookup returns no results.

## Steps to Replicate
1. Go to https://indivisible.org/events or https://indivisible.org/groups
2. Enter `11249` as the zip code
3. Map disappears and the following error shows up in the console:

<img width="786" alt="Screen Shot 2019-04-28 at 11 24 48 PM" src="https://user-images.githubusercontent.com/7892079/56875195-2e92c300-6a0d-11e9-9311-3f5ddd00c15f.png">

> selectors.js:52 Uncaught (in promise) TypeError: Cannot read property 'LAT' of null

## Investigation

The Firebase API that's being used for the zip code search returns returns `null` for `11249`:

> https://townhallproject-86312.firebaseio.com/zips/11249.json

And this eventually leads to a type error in the `getVisbleGroups` selector because `location` is `null` instead of an Object:

https://github.com/indivisible-org/indivisible-map/blob/3b319a10e37a409b3329dc5347623fd156366d1a/src/state/groups/selectors.js#L52-L54

Happy to help create a PR to fix it!

**Comment by meganrm** [comment]
Thanks yeah, it would be great if you could take this on

**Comment by walterbm** [comment]
@meganrm just opened up a PR (#149) to try and fix this issue. Let me know what you think!

**Comment by walterbm** [comment]
Fixed by #149
