### ISSUE TITLE
Indivisible Valley of the Sun email not updated on group map

### ISSUE THREAD

**Issue by mayaryair** [indivisible-org/indivisible-map#147]
In our system, Indivisible Valley of the Sun's email is listed as `indivisiblevos@gmail.com`. On the map, it's still listed as `ORAZVOS@gmail.com`. It was changed about a week ago but the change has not appeared. If this is an indication that all emails will not be updated, would love for that to be fixed as well!

**Comment by meganrm** [comment]
fixed
