### ISSUE TITLE
Param pass not working on pledge.indivisible.org

### ISSUE THREAD

**Issue by mayaryair** [indivisible-org/indivisible-map#148]
Params aren't passing through the event map on http://pledge.indivisible.org, which is hosted via Unbounce. I believe this is because the map on the page is hardcoded to filter to a specific issue focus, so the additional parameters won't attach to the URL. Is there a way to make this work? 

FYI we're setting this up referencing this doc: https://docs.google.com/document/d/1JdnoLBw-epoMsC3LZ6q-xt5Q2cEpCQZjJNZWZMTMGWE/edit

**Comment by meganrm** [comment]
What is the param you're trying to use that isn't working? When I go to that site the map is filtered to only show the # we are indivisible events. Is there something else you're trying to have happen?

**Comment by mayaryair** [comment]
Yeah, we're trying attach source params, for instance: http://pledge.indivisible.org/?source=test
We don't want that hardcoded into the map because we want to be able to send folks from different sources all to the same site. Right now, that param isn't passing through the map.

**Comment by meganrm** [comment]
it is being passed into the map `<iframe class="iframe" src="https://indivisible-org.github.io/indivisible-map/events?source=test" style="border:0px #000000 solid;" name="Event Map" scrolling="auto" align="bottom" height="800" width="930">
  </iframe>`.

**Comment by mayaryair** [comment]
The issue is that when a user clicks on an RSVP button on the map, that param isn't passed through. I want the source=test to appear on the event RSVP link, like `https://act.indivisible.org/event/we-are-indivisible-2020-kickoff/138870?source=test`

**Comment by meganrm** [comment]
I updated the code on the google sheet. it's in red.

**Comment by mayaryair** [comment]
Awesome thanks Megan! We'll test that out soon

**Comment by meganrm** [comment]
I updated the doc with a table that shows what keys you can use. To do a refcode, use 'source=test' as you have been.
