### ISSUE TITLE
Event missing from the event map

### ISSUE THREAD

**Issue by mayaryair** [indivisible-org/indivisible-map#154]
This event that was registered many days ago is missing from the event map. I haven't gone through and checked all events, so it's possible others are missing as well and this is a symptom of an issue. Need a fix ASAP! https://act.indivisible.org/event/attend-local-actions/144597

**Comment by meganrm** [comment]
this was a 'is_private': True, problem., but let me know if there are other events missing. Everything looks smooth on my end
